spring.datasource.jdbc-url=${DB_URL:jdbc:log4jdbc:mysql://localhost:3306/testDB?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8}
spring.datasource.tomcat.validation-query=SELECT 1
spring.datasource.username=${DB_USER:test}
spring.datasource.password=${DB_PASSWORD:test}
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.max-lifetime=58000

spring.main.web-application-type=none
netty.server.port = 38099
