spring.datasource.jdbc-url=jdbc:log4jdbc:mysql://192.168.0.101:3306/bithumb_bo?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
spring.datasource.tomcat.validation-query=SELECT 1
spring.datasource.username=wiezon
spring.datasource.password=wiezon1!
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.max-lifetime=58000

spring.main.web-application-type=none
netty.server.port = 38099
#10min
access.token.expiration.time=600000
#180day
refresh.token.expiration.time=15552000000
coNo=1238640537
mts.url=http://192.168.0.102:38888/taskapi
# Front NonUI Keyin Payment URL
front.payment.keyin.url=http://192.168.0.102:38059/payment/v1/keyin