spring.datasource.jdbc-url=jdbc:log4jdbc:mysql://192.168.0.101:3306/testDB?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
spring.datasource.tomcat.validation-query=SELECT 1
spring.datasource.username=test
spring.datasource.password=test
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.max-lifetime=58000

spring.main.web-application-type=none
netty.server.port = 38099
